name: Issue and PR Automation
on:
  issues:
    types: [opened, reopened, transferred]
  pull_request:
    types: [opened, reopened]

jobs:
  add-to-project:
    name: Issue and PR Automation
    uses: brobeson/IssueAutomation/.github/workflows/issue_automation.yaml@main
    secrets:
      personal_access_token: ${{ secrets.ADD_TO_PROJECT_PAT }}
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Add to project
    #     uses: actions/add-to-project@v2
    #     with:
    #       project-url: https://github.com/users/brobeson/projects/17
    #       github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
